[build]
base = "frontend"
command = "yarn install && yarn build"
publish = "build"

[build.environment]
NODE_VERSION = "20"

# SPA redirect
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Form handling
[build.processing.html]
pretty_urls = true

# Ensure forms are processed
[dev]
framework = "#custom"
command = "yarn start"
targetPort = 3000
port = 8888
publish = "build"
autoLaunch = true